### ISSUE TITLE
AnalyseParticles

### ISSUE THREAD

**Issue by stefankraemer91** [arve0/fijibin#2]
Hello,

first of all, very nice python package. Very helpful for a lot of things. However, I experience some problems using the following code insdide one of my macros:

` run("Analyze Particles...", "size=100-600 pixel circularity=0.80-1.00 show=Overlay exclude add")`

I always get the following error:
```
fijibin ERROR: Fiji did not successfully run macro /var/folders/n0/nspdv1js5tg4wz_g8c4wz6d40000gp/T/tmprkogn4jc.ijm
fijibin Try running script with `DEBUG=fijibin python your_script.py`
```

My complete macro locks like this:
```
import fijibin.macro as macro
particle= """open("PATH_TO_16bit_tif_PICTURE");
setAutoThreshold("Default");
setOption("BlackBackground", false);
run("Convert to Mask");
run("Close");
run("ROI Manager...");
run("Analyze Particles...", "size=100-600 pixel circularity=0.80-1.00 show=Overlay exclude include");
"""
macro.run(particle)
```

I think this might be a bug in your code. I tried a lot of things and the program always crashes after reaching the analyse particles command.

Thanks and greetings

**Comment by arve0** [comment]
Hi! Thanks for reporting.
I do not currently have fijibin setup on my machine, can you paste output of `DEBUG=fijibin python your_script.py`?
